default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "zssn_development") %>

test:
  <<: *default
  database: zssn_test

production:
  <<: *default
  database: zssn_production
  username: zssn
  password: <%= ENV["ZSSN_DATABASE_PASSWORD"] %>
