default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV", "zssn_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "zssn_test") %>

production:
  primary: &primary_production
    <<: *default
    database: zssn_production
    username: zssn
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: zssn_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: zssn_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: zssn_production_cable
    migrations_paths: db/cable_migrate
